# Generated by Django 6.1 on 2026-09-01 14:56

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('LOGIN_OK', 'Login OK'), ('LOGIN_NEGADO', 'Login negado'), ('UP_BOLETO', 'Upload de boleto'), ('UP_CONTRATO', 'Upload de contrato'), ('DOWNLOAD', 'Download de arquivo'), ('DL_NEGADO', 'Download negado'), ('STATUS', 'Mudança de status'), ('CRUD', 'Cadastro alterado')], max_length=12)),
                ('ator_email', models.CharField(blank=True, max_length=255)),
                ('detalhe', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Sempre dia 1 do mês')),
                ('arquivo', models.FileField(upload_to=core.models._upload_boleto)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('enviado_por', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido — aguardando verificação'), ('APROVADO', 'Valor confere — enviado p/ pagamento'), ('DIVERGENTE', 'Valor divergente — aguardando contato'), ('MANUAL', 'Verificar manualmente (IA não leu)'), ('PAGO', 'Pago'), ('SUBSTITUIDO', 'Substituído por novo arquivo')], default='RECEBIDO', max_length=12)),
                ('valor_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_extraido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ia_resposta', models.TextField(blank=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('verificado_em', models.DateTimeField(blank=True, null=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-competencia', 'prestador__nome'],
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(blank=True, help_text='Letra do legado (A, B, C...)', max_length=5)),
                ('id_endereco_legado', models.IntegerField(blank=True, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('ok', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('boleto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='core.boleto')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='boleto',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='core.posto'),
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('modo_boleto', models.CharField(choices=[('POR_POSTO', 'Um boleto por posto'), ('UNICO', 'Um boleto único (contra um posto)')], default='POR_POSTO', max_length=10)),
                ('valor_unico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('posto_cobranca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.posto')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models._upload_contrato)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('enviado_por', models.EmailField(blank=True, max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='core.posto')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='core.prestador')),
            ],
            options={
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.AddField(
            model_name='boleto',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='core.prestador'),
        ),
        migrations.CreateModel(
            name='UsuarioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('is_admin', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.prestador')),
            ],
            options={
                'verbose_name': 'usuário permitido',
                'verbose_name_plural': 'usuários permitidos',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='PrestadorPosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.posto')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.prestador')),
            ],
            options={
                'ordering': ['posto__nome'],
                'unique_together': {('prestador', 'posto')},
            },
        ),
    ]
