# Generated by Django 6.1 on 2026-09-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_postos'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='boleto',
            name='linha_digitavel',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
