# Generated by Django 6.1 on 2026-09-01 15:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_boleto_chave_pix_boleto_linha_digitavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('remetente', models.CharField(max_length=255)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('resultado', models.CharField(choices=[('BOLETO', 'Boleto(s) criado(s)'), ('SEM_PREST', 'Remetente sem cadastro'), ('SEM_CONT', 'Sem PDF e sem linha digitável')], max_length=10)),
                ('detalhe', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='boleto',
            name='valor_livre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boleto',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=core.models._upload_boleto),
        ),
    ]
