# Generated by Django 6.1 on 2026-09-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailrecebido_boleto_valor_livre_boleto_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
