# Generated by Django 6.1 on 2026-09-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boleto_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='core.posto'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vigencia_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
