# Generated by Django 6.1 on 2026-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_prestador_excluido_em_alter_contrato_posto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=60, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='boleto',
            name='ia_confianca',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido — aguardando verificação'), ('APROVADO', 'Valor confere — enviado p/ pagamento'), ('DIVERGENTE', 'Valor divergente — aguardando contato'), ('MANUAL', 'Verificar manualmente (IA não leu)'), ('PAGO', 'Pago'), ('SUBSTITUIDO', 'Substituído por novo arquivo'), ('DUPLICADO', 'Duplicado — competência já aprovada/paga')], default='RECEBIDO', max_length=12),
        ),
    ]
