# Generated by Django 6.1 on 2026-09-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_posto_excluido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='posto',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
