# Generated by Django 6.1 on 2026-09-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_razoes_cnpjs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=160)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcelas_total', models.PositiveSmallIntegerField()),
                ('primeira_competencia', models.DateField(help_text='Mês da parcela 1 (dia 1)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.posto')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales', to='core.prestador')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
