# Generated by Django 6.1 on 2026-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido — aguardando verificação'), ('APROVADO', 'Valor confere — enviado p/ pagamento'), ('DIVERGENTE', 'Valor divergente — aguardando contato'), ('MANUAL', 'Verificar manualmente'), ('PAGO', 'Pago'), ('SUBSTITUIDO', 'Substituído por novo arquivo'), ('DUPLICADO', 'Duplicado — competência já aprovada/paga')], default='RECEBIDO', max_length=12),
        ),
    ]
