# Generated by Django 6.1 on 2026-09-01 18:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_boleto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='nota_fiscal',
            field=models.FileField(blank=True, null=True, upload_to=core.models._upload_boleto),
        ),
        migrations.AddField(
            model_name='boleto',
            name='nota_fiscal_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prestador',
            name='exige_nf',
            field=models.BooleanField(default=False, verbose_name='Exigir nota fiscal anexa'),
        ),
    ]
