# Generated by Django 6.1 on 2026-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_boleto_nota_fiscal_boleto_nota_fiscal_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido — aguardando verificação'), ('APROVADO', 'Valor confere — enviado p/ pagamento'), ('DIVERGENTE', 'Valor divergente — aguardando contato'), ('MANUAL', 'Verificar manualmente'), ('PAGO', 'Pago'), ('SUBSTITUIDO', 'Substituído por novo arquivo'), ('DUPLICADO', 'Duplicado — competência já aprovada/paga'), ('DESCARTADO', 'Descartado pelo admin')], default='RECEBIDO', max_length=12),
        ),
    ]
