# Generated by Django 6.1 on 2026-09-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_boleto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopermitido',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuariopermitido',
            name='api_token_criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
