# Generated by Django 6.1 on 2026-09-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_usuariopermitido_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
