# Generated by Django 6.1 on 2026-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_boleto_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='gerente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='posto',
            name='gerente_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
