# Generated by Django 6.1 on 2026-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_posto_gerente_email_posto_gerente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='fin_recebido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido — aguardando verificação'), ('APROVADO', 'Valor confere — enviado p/ pagamento'), ('FIN_RECEBIDO', 'Recebido pelo financeiro'), ('DIVERGENTE', 'Valor divergente — aguardando contato'), ('MANUAL', 'Verificar manualmente'), ('PAGO', 'Pago'), ('SUBSTITUIDO', 'Substituído por novo arquivo'), ('DUPLICADO', 'Duplicado — competência já aprovada/paga'), ('DESCARTADO', 'Descartado pelo admin')], default='RECEBIDO', max_length=14),
        ),
        migrations.AlterField(
            model_name='emailrecebido',
            name='resultado',
            field=models.CharField(choices=[('BOLETO', 'Boleto(s) criado(s)'), ('SEM_PREST', 'Remetente sem cadastro'), ('SEM_CONT', 'Sem PDF e sem linha digitável'), ('FIN', 'Confirmação do financeiro')], max_length=10),
        ),
    ]
