# Generated by Django 6.1 on 2026-09-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_boleto_fin_recebido_em_alter_boleto_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='parcial',
            field=models.BooleanField(default=False),
        ),
    ]
