# Generated by Django 6.1 on 2026-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_boleto_parcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='gerente_fixo',
            field=models.BooleanField(default=False),
        ),
    ]
