# Generated by Django 6.1 on 2026-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_posto_gerente_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='pagamento_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='pagamento_enviado_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
