# Generated by Django 6.1 on 2026-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_boleto_pagamento_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='emails_aviso',
            field=models.CharField(blank=True, help_text='Separe vários por vírgula', max_length=300),
        ),
    ]
