# Generated by Django 6.1 on 2026-09-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_prestador_emails_aviso'),
    ]

    def _preencher(apps, schema_editor):
        Prestador = apps.get_model('core', 'Prestador')
        for p in Prestador.objects.filter(representante=''):
            p.representante = p.nome
            p.save(update_fields=['representante'])

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='representante',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='prestador',
            name='representante_nome_social',
            field=models.CharField(blank=True, max_length=120),
        ),
            migrations.RunPython(_preencher, migrations.RunPython.noop),
    ]
