# Generated by Django 6.1 on 2026-09-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_prestador_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='dia_pagamento',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Data prevista para pagamento (dia do mês)'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vencimento do boleto (dia do mês)'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='regime_pagamento',
            field=models.CharField(choices=[('VIGENTE', 'Pagamento no mês vigente — serviço e pagamento no mesmo mês'), ('POSTERIOR', 'Pagamento no mês seguinte à prestação do serviço')], default='VIGENTE', max_length=10),
        ),
    ]
