# Generated by Django 6.1 on 2026-09-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_prestador_regime_prazos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteDiferenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modo', models.CharField(choices=[('DINHEIRO', 'Pago em dinheiro'), ('NAO_PAGO', 'Não será pago')], max_length=10)),
                ('por', models.EmailField(blank=True, max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.posto')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='core.prestador')),
            ],
            options={
                'unique_together': {('prestador', 'posto', 'competencia')},
            },
        ),
    ]
