# Generated by Django 6.1 on 2026-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ajuste_diferenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='representante_cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
