# Generated by Django 6.1 on 2026-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_prestador_representante_cpf'),
    ]

    def _todos_posterior(apps, schema_editor):
        # Decisão de 02/09/2026: todos pagam no mês seguinte ao serviço;
        # a exceção (Erick) é marcada à mão no cadastro.
        apps.get_model('core', 'Prestador').objects.update(
            regime_pagamento='POSTERIOR')

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='regime_pagamento',
            field=models.CharField(choices=[('VIGENTE', 'Pagamento no mês vigente — serviço e pagamento no mesmo mês'), ('POSTERIOR', 'Pagamento no mês seguinte à prestação do serviço')], default='POSTERIOR', max_length=10),
        ),
            migrations.RunPython(_todos_posterior, migrations.RunPython.noop),
    ]
