# Generated by Django 6.1 on 2026-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_regime_padrao_posterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='bairro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='prestador',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='cidade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='prestador',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço (rua, nº, compl.)'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
