# Generated by Django 6.1 on 2026-09-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_prestador_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='abertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail da empresa'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prestador',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razão social'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='receita_consultado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='situacao_cadastral',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='prestador',
            name='socios',
            field=models.TextField(blank=True, help_text='um por linha'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='telefone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
