# Generated by Django 6.1 on 2026-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_prestador_ficha_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='aprovado_por',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
