# Generated by Django 6.1.1 on 2026-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_prestador_recebe_por_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='arquivo_removido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='arquivo_removido_motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
