# Generated by Django 6.1 on 2026-10-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_boleto_arquivo_removido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='nao_reconhecido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='nao_reconhecido_motivo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido — aguardando verificação'), ('APROVADO', 'Valor confere — enviado p/ pagamento'), ('FIN_RECEBIDO', 'Recebido pelo financeiro'), ('DIVERGENTE', 'Valor divergente — aguardando contato'), ('MANUAL', 'Verificar manualmente'), ('PAGO', 'Pago'), ('SUBSTITUIDO', 'Substituído por novo arquivo'), ('DUPLICADO', 'Duplicado — competência já aprovada/paga'), ('DESCARTADO', 'Descartado pelo admin'), ('NAO_RECONHECIDO', 'Dívida não reconhecida — prestador avisado')], default='RECEBIDO', max_length=16),
        ),
    ]
