# Generated by Django 6.1 on 2026-10-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_boleto_nao_reconhecido'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='email_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='core.emailrecebido'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='origem',
            field=models.CharField(blank=True, choices=[('API', 'API'), ('PORTAL', 'Plataforma'), ('PAINEL', 'Plataforma (cadastro do admin)'), ('EMAIL', 'E-mail')], max_length=8),
        ),
        migrations.AddField(
            model_name='emailrecebido',
            name='anexos',
            field=models.TextField(blank=True, help_text='Um nome por linha'),
        ),
        migrations.AddField(
            model_name='emailrecebido',
            name='corpo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailrecebido',
            name='corpo_buscado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecebido',
            name='enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecebido',
            name='para',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
