# Generated by Django 6.1 on 2026-10-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_origem_dos_boletos_antigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='boletos/')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('substituida_em', models.DateTimeField(auto_now_add=True)),
                ('substituida_por', models.CharField(blank=True, max_length=255)),
                ('via', models.CharField(blank=True, choices=[('API', 'API'), ('PORTAL', 'Plataforma'), ('PAINEL', 'Plataforma (cadastro do admin)'), ('EMAIL', 'E-mail')], max_length=8)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_anteriores', to='core.boleto')),
            ],
            options={
                'ordering': ['substituida_em', 'pk'],
            },
        ),
    ]
