from django.urls import path

from . import api, views, views_auth, views_painel

urlpatterns = [
    path('', views.home, name='home'),
    path('sem-acesso/', views.sem_acesso, name='sem_acesso'),
    # Login por e-mail+senha (PJ sem idCamim) — convive com o IDCamim.
    path('entrar/', views_auth.entrar, name='entrar'),
    path('sair/', views_auth.sair, name='sair'),
    path('senha/recuperar/', views_auth.recuperar_senha,
         name='recuperar_senha'),
    path('senha/definir/<uidb64>/<token>/', views_auth.definir_senha,
         name='definir_senha'),
    path('boleto/', views.anexar_boleto, name='anexar_boleto'),
    path('contratos/', views.contratos_postos, name='contratos_postos'),
    path('contratos/<int:posto_id>/', views.contratos_lista,
         name='contratos_lista'),
    path('arquivo/<str:tipo>/<int:pk>/', views.baixar_arquivo,
         name='baixar_arquivo'),

    path('sair-ver-como/', views.sair_ver_como, name='sair_ver_como'),
    path('api/boletos/', api.boletos, name='api_boletos'),
    path('api/boletos/<int:pk>/nota/', api.nota, name='api_boleto_nota'),
    # pelo mês ("2026-10") em vez do id — vem DEPOIS da rota <int:pk>
    path('api/boletos/<str:competencia>/nota/', api.nota_do_mes,
         name='api_nota_do_mes'),
    path('api/boletos/<str:competencia>/boleto/', api.boleto_do_mes,
         name='api_boleto_do_mes'),

    path('painel/', views_painel.dashboard, name='painel_dashboard'),
    path('painel/parciais-status/', views_painel.parciais_status,
         name='painel_parciais_status'),
    path('painel/boleto/novo/', views_painel.boleto_novo,
         name='painel_boleto_novo'),
    path('painel/verificar-email/', views_painel.verificar_email_agora,
         name='painel_verificar_email'),
    path('painel/boleto/<int:pk>/editar/', views_painel.boleto_editar,
         name='painel_boleto_editar'),
    path('painel/ver-como/<int:pk>/', views_painel.ver_como,
         name='painel_ver_como'),
    path('painel/ajuste-diferenca/', views_painel.ajuste_diferenca,
         name='painel_ajuste_diferenca'),
    path('painel/boleto/<int:pk>/<str:acao>/', views_painel.boleto_acao,
         name='painel_boleto_acao'),
    path('painel/prestadores/', views_painel.prestadores,
         name='painel_prestadores'),
    path('painel/prestadores/<int:pk>/', views_painel.prestador_detalhe,
         name='painel_prestador'),
    path('painel/prestadores/<int:pk>/pagar-todos/',
         views_painel.pagar_todos, name='painel_pagar_todos'),
    path('painel/prestadores/<int:pk>/excluir/',
         views_painel.prestador_excluir, name='painel_prestador_excluir'),
    path('painel/prestadores/<int:pk>/restaurar/',
         views_painel.prestador_restaurar, name='painel_prestador_restaurar'),
    path('painel/postos/', views_painel.postos, name='painel_postos'),
    path('painel/usuarios/', views_painel.usuarios, name='painel_usuarios'),
    path('painel/gerentes/', views_painel.gerentes, name='painel_gerentes'),
    path('painel/config/', views_painel.configuracoes, name='painel_config'),
    path('painel/notificacoes/', views_painel.preferencias_notificacao,
         name='painel_notificacoes'),
    path('painel/emails/', views_painel.emails_log, name='painel_emails'),
    path('painel/emails/nao-reconhecidos/',
         views_painel.emails_nao_reconhecidos,
         name='painel_emails_nao_reconhecidos'),
    path('painel/emails/<int:pk>/', views_painel.email_detalhe,
         name='painel_email_detalhe'),
    path('painel/emails/recebidos/<int:pk>/',
         views_painel.email_recebido_detalhe, name='painel_email_recebido'),
    path('painel/auditoria/', views_painel.auditoria, name='painel_auditoria'),
]
